apiVersion: v1
kind: Service
metadata:
  name: {{ include "bento.fullname" . }}
  labels:
    {{- include "bento.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    {{- include "bento.selectorLabels" . | nindent 4 }}
