{{- if .Values.secret_key_base.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "manyfold.fullname" . }}
  labels:
    {{- include "manyfold.labels" . | nindent 4 }}
data:
  SECRET_KEY_BASE: {{ .Values.secret_key_base.secret | b64enc | quote }}
{{- end }}
